package:
  name: pygdf
  version: 0.1.0a3 

source:
  - git_rev: v0.1.0a3
    git_url: https://github.com/gpuopenanalytics/pygdf 
    folder: pygdf 
  - git_rev: v0.1.0a3 
    git_url: https://github.com/gpuopenanalytics/libgdf  
    folder: libgdf 
    patches: 
      - libgdf_cmake.patch
  - git_rev: apache-arrow-0.11.0 
    git_url: https://github.com/apache/arrow.git 
    folder: repos/arrow 

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - numba 0.41.0dev0
    - numpy 1.14.5
    - pandas 0.20.3
    - git
    - cmake
    - make
    - cython
    - boost 
    - py 
    - cffi
    - gfortran_impl_linux-ppc64le 
    - flex
    - bison
    - pkg-config
  run:
    - python
    - setuptools
    - pandas 0.20.*
    - numba>=0.40.0dev
    - cffi

test:
  requires:
    - distributed >=1.22.1
    - pytest
  imports:
    - pygdf

about:
  home: http://gpuopenanalytics.com/
  license: Apache
  # license_file: LICENSE
  summary: GPU Dataframe core library
